version: '3.7'

services:
  app:
    container_name: "MMAFighters"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    extra_hosts:
      - 'postgresql:host-gateway'
    ports:
      - 8000:8000