"""add relationships

Revision ID: 41905a9bfa53
Revises: 
Create Date: 2024-03-02 15:01:39.120471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41905a9bfa53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fighters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('base_style', sa.String(), nullable=False),
    sa.Column('promotion', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight_category', sa.String(), nullable=False),
    sa.Column('arm_span', sa.Integer(), nullable=False),
    sa.Column('wins_count', sa.Integer(), nullable=False),
    sa.Column('wins_knockouts_count', sa.Integer(), nullable=False),
    sa.Column('wins_submissions_count', sa.Integer(), nullable=False),
    sa.Column('wins_judges_decisions_count', sa.Integer(), nullable=False),
    sa.Column('defeats_count', sa.Integer(), nullable=False),
    sa.Column('defeats_knockouts_count', sa.Integer(), nullable=False),
    sa.Column('defeats_submissions_count', sa.Integer(), nullable=False),
    sa.Column('defeats_judges_decisions_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fights',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_fighter_id', sa.BigInteger(), nullable=False),
    sa.Column('second_fighter_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_fighter_id'], ['fighters.id'], ),
    sa.ForeignKeyConstraint(['second_fighter_id'], ['fighters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fights')
    op.drop_table('users')
    op.drop_table('fighters')
    # ### end Alembic commands ###
